name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim-version: ['1.6.8', '1.6.x', '2.0.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: nimble test --mm:orc -y
    - run: nimble test --threads:on --mm:orc -y
